<?xml version="1.0" encoding="utf-8"?><Database Name="QLPHS" Class="EntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADMINPC;Initial Catalog=QLPHS;Integrated Security=True" SettingsObjectName="Core.Properties.Settings" SettingsPropertyName="QLPHSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADONDAILY" Member="CHITIETHOADONDAILies">
    <Type Name="CHITIETHOADONDAILY">
      <Column Name="masohoadon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONDAILY_CHITIETHOADONDAILY" Member="HOADONDAILY" ThisKey="masohoadon" OtherKey="masohoadon" Type="HOADONDAILY" IsForeignKey="true" />
      <Association Name="SACH_CHITIETHOADONDAILY" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THEKHO" Member="THEKHOs">
    <Type Name="THEKHO">
      <Column Name="ngayghi" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="SACH_THEKHO" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADONNXB" Member="CHITIETHOADONNXBs">
    <Type Name="CHITIETHOADONNXB">
      <Column Name="masohoadon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONNXB_CHITIETHOADONNXB" Member="HOADONNXB" ThisKey="masohoadon" OtherKey="masohoadon" Type="HOADONNXB" IsForeignKey="true" />
      <Association Name="SACH_CHITIETHOADONNXB" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs">
    <Type Name="CHITIETPHIEUNHAP">
      <Column Name="masophieunhap" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CHITIETPHIEUNHAP" Member="PHIEUNHAP" ThisKey="masophieunhap" OtherKey="masophieunhap" Type="PHIEUNHAP" IsForeignKey="true" />
      <Association Name="SACH_CHITIETPHIEUNHAP" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETPHIEUXUAT" Member="CHITIETPHIEUXUATs">
    <Type Name="CHITIETPHIEUXUAT">
      <Column Name="masophieuxuat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUXUAT_CHITIETPHIEUXUAT" Member="PHIEUXUAT" ThisKey="masophieuxuat" OtherKey="masophieuxuat" Type="PHIEUXUAT" IsForeignKey="true" />
      <Association Name="SACH_CHITIETPHIEUXUAT" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONGNODAILY" Member="CONGNODAILies">
    <Type Name="CONGNODAILY">
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masodaily" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thang" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="DAILY_CONGNODAILY" Member="DAILY" ThisKey="masodaily" OtherKey="masodaily" Type="DAILY" IsForeignKey="true" />
      <Association Name="SACH_CONGNODAILY" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONGNONXB" Member="CONGNONXBs">
    <Type Name="CONGNONXB">
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masonxb" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="thang" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="NXB_CONGNONXB" Member="NXB" ThisKey="masonxb" OtherKey="masonxb" Type="NXB" IsForeignKey="true" />
      <Association Name="SACH_CONGNONXB" Member="SACH" ThisKey="masosach" OtherKey="masosach" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DAILY" Member="DAILies">
    <Type Name="DAILY">
      <Column Name="masodaily" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sodienthoai" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="sotaikhoan" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="masonguoidung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nganhang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DAILY_CONGNODAILY" Member="CONGNODAILies" ThisKey="masodaily" OtherKey="masodaily" Type="CONGNODAILY" />
      <Association Name="DAILY_HOADONDAILY" Member="HOADONDAILies" ThisKey="masodaily" OtherKey="masodaily" Type="HOADONDAILY" />
      <Association Name="DAILY_PHIEUXUAT" Member="PHIEUXUATs" ThisKey="masodaily" OtherKey="masodaily" Type="PHIEUXUAT" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONDAILY" Member="HOADONDAILies">
    <Type Name="HOADONDAILY">
      <Column Name="masohoadon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masodaily" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONDAILY_CHITIETHOADONDAILY" Member="CHITIETHOADONDAILies" ThisKey="masohoadon" OtherKey="masohoadon" Type="CHITIETHOADONDAILY" />
      <Association Name="DAILY_HOADONDAILY" Member="DAILY" ThisKey="masodaily" OtherKey="masodaily" Type="DAILY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONNXB" Member="HOADONNXBs">
    <Type Name="HOADONNXB">
      <Column Name="masohoadon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masonxb" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADONNXB_CHITIETHOADONNXB" Member="CHITIETHOADONNXBs" ThisKey="masohoadon" OtherKey="masohoadon" Type="CHITIETHOADONNXB" />
      <Association Name="NXB_HOADONNXB" Member="NXB" ThisKey="masonxb" OtherKey="masonxb" Type="NXB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LINHVUC" Member="LINHVUCs">
    <Type Name="LINHVUC">
      <Column Name="masolinhvuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LINHVUC_SACH" Member="SACHes" ThisKey="masolinhvuc" OtherKey="masolinhvuc" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="masonguoidung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tennguoidung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tendaydu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phanquyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NXB" Member="NXBs">
    <Type Name="NXB">
      <Column Name="masonxb" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sodienthoai" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="sotaikhoan" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nganhang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NXB_CONGNONXB" Member="CONGNONXBs" ThisKey="masonxb" OtherKey="masonxb" Type="CONGNONXB" />
      <Association Name="NXB_HOADONNXB" Member="HOADONNXBs" ThisKey="masonxb" OtherKey="masonxb" Type="HOADONNXB" />
      <Association Name="NXB_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="masonxb" OtherKey="masonxb" Type="PHIEUNHAP" />
      <Association Name="NXB_SACH" Member="SACHes" ThisKey="masonxb" OtherKey="masonxb" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="masophieunhap" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masonxb" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nguoigiaosach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs" ThisKey="masophieunhap" OtherKey="masophieunhap" Type="CHITIETPHIEUNHAP" />
      <Association Name="NXB_PHIEUNHAP" Member="NXB" ThisKey="masonxb" OtherKey="masonxb" Type="NXB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUXUAT" Member="PHIEUXUATs">
    <Type Name="PHIEUXUAT">
      <Column Name="masophieuxuat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masodaily" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nguoinhasach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUXUAT_CHITIETPHIEUXUAT" Member="CHITIETPHIEUXUATs" ThisKey="masophieuxuat" OtherKey="masophieuxuat" Type="CHITIETPHIEUXUAT" />
      <Association Name="DAILY_PHIEUXUAT" Member="DAILY" ThisKey="masodaily" OtherKey="masodaily" Type="DAILY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="masosach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="masonxb" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masolinhvuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tensach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tacgia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="giaban" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="gianhap" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hinhanh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mota" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="SACH_CHITIETHOADONDAILY" Member="CHITIETHOADONDAILies" ThisKey="masosach" OtherKey="masosach" Type="CHITIETHOADONDAILY" />
      <Association Name="SACH_THEKHO" Member="THEKHOs" ThisKey="masosach" OtherKey="masosach" Type="THEKHO" />
      <Association Name="SACH_CHITIETHOADONNXB" Member="CHITIETHOADONNXBs" ThisKey="masosach" OtherKey="masosach" Type="CHITIETHOADONNXB" />
      <Association Name="SACH_CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs" ThisKey="masosach" OtherKey="masosach" Type="CHITIETPHIEUNHAP" />
      <Association Name="SACH_CHITIETPHIEUXUAT" Member="CHITIETPHIEUXUATs" ThisKey="masosach" OtherKey="masosach" Type="CHITIETPHIEUXUAT" />
      <Association Name="SACH_CONGNODAILY" Member="CONGNODAILies" ThisKey="masosach" OtherKey="masosach" Type="CONGNODAILY" />
      <Association Name="SACH_CONGNONXB" Member="CONGNONXBs" ThisKey="masosach" OtherKey="masosach" Type="CONGNONXB" />
      <Association Name="LINHVUC_SACH" Member="LINHVUC" ThisKey="masolinhvuc" OtherKey="masolinhvuc" Type="LINHVUC" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NXB_SACH" Member="NXB" ThisKey="masonxb" OtherKey="masonxb" Type="NXB" IsForeignKey="true" />
    </Type>
  </Table>
</Database>